export const UPDATE_LIST = "UPDATE_LIST";
export const UPDATE_FILTERED_LIST = "UPDATE_FILTERED_LIST";
export const UPDATE_FETCH_STATUS = "UPDATE_FETCH_STATUS";
export const UPDATE_FETCH_ERROR = "UPDATE_FETCH_ERROR";
